//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.enlace.v1;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.AfiliadosCompensados;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Anec;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Asopagos;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Bdua;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.ConsejoProfesional;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Contraloria;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Copnia;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Cpae;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Cpip;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Cpnaa;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Cpnt;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.DianRut;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Icetex;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Identificacion;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.InfraccionesTransito;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Persona;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Procuraduria;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.PuestoVotacion;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.RamaJudicial;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Ruaf;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.RuesCamaras;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.Runt;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.RuntPlaca;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.SisbenPuntaje;
import com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.TramiteCedula;

@WebService(name = "ConsultaFuentesPublicasExternas", targetNamespace = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0")
@XmlSeeAlso({
    com.grupobancolombia.ents.common.genericexception.v2.ObjectFactory.class,
    com.grupobancolombia.ents.soi.coreextensions.v2.ObjectFactory.class,
    com.grupobancolombia.ents.soi.messageformat.v2.ObjectFactory.class,
    com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.ObjectFactory.class
})
public interface ConsultaFuentesPublicasExternas {


    /**
     * 
     * @param infraccionesTransitoSimit
     * @param cpnaa
     * @param ruesCamaras
     * @param copnia
     * @param sisbenPuntaje
     * @param ramaJudicial
     * @param placaVehiculo
     * @param runt
     * @param procuraduria
     * @param anec
     * @param bdua
     * @param cpae
     * @param cpip
     * @param asopagos
     * @param identificacion
     * @param contraloria
     * @param ruaf
     * @param fuente
     * @param nombreCompleto
     * @param consejoProfesional
     * @param cpnt
     * @param tramiteCedula
     * @param puestoVotacion
     * @param afiliadosCompensados
     * @param runtPlaca
     * @param icetex
     * @param dianRut
     * @throws SystemExceptionMsg
     */
    @WebMethod(action = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0/consultarFuentesExternas")
    @RequestWrapper(localName = "consultarFuentesExternas", targetNamespace = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", className = "com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.ConsultarFuentesExternas")
    @ResponseWrapper(localName = "consultarFuentesExternasResponse", targetNamespace = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", className = "com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1.ConsultarFuentesExternasResponse")
    public void consultarFuentesExternas(
        @WebParam(name = "identificacion", targetNamespace = "")
        Identificacion identificacion,
        @WebParam(name = "placaVehiculo", targetNamespace = "")
        String placaVehiculo,
        @WebParam(name = "fuente", targetNamespace = "")
        List<String> fuente,
        @WebParam(name = "bdua", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Bdua> bdua,
        @WebParam(name = "ruaf", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Ruaf> ruaf,
        @WebParam(name = "nombreCompleto", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Persona> nombreCompleto,
        @WebParam(name = "procuraduria", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Procuraduria> procuraduria,
        @WebParam(name = "sisbenPuntaje", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<SisbenPuntaje> sisbenPuntaje,
        @WebParam(name = "dianRut", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<DianRut> dianRut,
        @WebParam(name = "puestoVotacion", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<PuestoVotacion> puestoVotacion,
        @WebParam(name = "contraloria", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Contraloria> contraloria,
        @WebParam(name = "copnia", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Copnia> copnia,
        @WebParam(name = "asopagos", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Asopagos> asopagos,
        @WebParam(name = "ramaJudicial", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<RamaJudicial> ramaJudicial,
        @WebParam(name = "tramiteCedula", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<TramiteCedula> tramiteCedula,
        @WebParam(name = "infraccionesTransitoSimit", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<InfraccionesTransito> infraccionesTransitoSimit,
        @WebParam(name = "cpae", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Cpae> cpae,
        @WebParam(name = "consejoProfesional", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ConsejoProfesional> consejoProfesional,
        @WebParam(name = "cpnaa", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Cpnaa> cpnaa,
        @WebParam(name = "anec", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Anec> anec,
        @WebParam(name = "cpip", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Cpip> cpip,
        @WebParam(name = "icetex", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Icetex> icetex,
        @WebParam(name = "cpnt", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Cpnt> cpnt,
        @WebParam(name = "ruesCamaras", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<RuesCamaras> ruesCamaras,
        @WebParam(name = "runt", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Runt> runt,
        @WebParam(name = "runtPlaca", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<RuntPlaca> runtPlaca,
        @WebParam(name = "afiliadosCompensados", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<AfiliadosCompensados> afiliadosCompensados)
        throws SystemExceptionMsg
    ;

}
