//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for Camara complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Camara">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ubicacionFuente" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Ubicacion" minOccurs="0"/>
 *         &lt;element name="nombrePersona" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Persona" minOccurs="0"/>
 *         &lt;element name="categoriaPersona" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="camaraComercio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="razonSocialEstablecimiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="siglaEstablecimiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroMatricula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estadoMatricula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="annoUltimaRenovacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaMatricula" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="fechaCancelacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="categoriaMatricula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoSociedad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoOrganizacionEstablecimiento" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numEmpleados" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="esAfiliado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="actividadEconomica" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}ActividadEconomica" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="representanteLegal" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}RepresentanteLegal" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Camara", propOrder = { "ubicacionFuente", "nombrePersona", "categoriaPersona", "camaraComercio",
		"razonSocialEstablecimiento", "siglaEstablecimiento", "numeroMatricula", "estadoMatricula",
		"annoUltimaRenovacion", "fechaMatricula", "fechaCancelacion", "categoriaMatricula", "tipoSociedad",
		"tipoOrganizacionEstablecimiento", "numEmpleados", "esAfiliado", "actividadEconomica", "representanteLegal" })
public class Camara {

	protected Ubicacion ubicacionFuente;
	protected Persona nombrePersona;
	protected String categoriaPersona;
	protected String camaraComercio;
	protected String razonSocialEstablecimiento;
	protected String siglaEstablecimiento;
	protected String numeroMatricula;
	protected String estadoMatricula;
	protected String annoUltimaRenovacion;
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar fechaMatricula;
	@XmlSchemaType(name = "date")
	protected XMLGregorianCalendar fechaCancelacion;
	protected String categoriaMatricula;
	protected String tipoSociedad;
	protected String tipoOrganizacionEstablecimiento;
	protected String numEmpleados;
	protected String esAfiliado;
	@XmlElementWrapper(name = "actividadEconomica")
	@XmlElement(name = "ActividadEconomica")
	protected List<ActividadEconomica> actividadEconomica;
	protected RepresentanteLegal representanteLegal;

	/**
	 * Gets the value of the ubicacionFuente property.
	 * 
	 * @return possible object is {@link Ubicacion }
	 * 
	 */
	public Ubicacion getUbicacionFuente() {
		return ubicacionFuente;
	}

	/**
	 * Sets the value of the ubicacionFuente property.
	 * 
	 * @param value
	 *            allowed object is {@link Ubicacion }
	 * 
	 */
	public void setUbicacionFuente(Ubicacion value) {
		this.ubicacionFuente = value;
	}

	/**
	 * Gets the value of the nombrePersona property.
	 * 
	 * @return possible object is {@link Persona }
	 * 
	 */
	public Persona getNombrePersona() {
		return nombrePersona;
	}

	/**
	 * Sets the value of the nombrePersona property.
	 * 
	 * @param value
	 *            allowed object is {@link Persona }
	 * 
	 */
	public void setNombrePersona(Persona value) {
		this.nombrePersona = value;
	}

	/**
	 * Gets the value of the categoriaPersona property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoriaPersona() {
		return categoriaPersona;
	}

	/**
	 * Sets the value of the categoriaPersona property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoriaPersona(String value) {
		this.categoriaPersona = value;
	}

	/**
	 * Gets the value of the camaraComercio property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCamaraComercio() {
		return camaraComercio;
	}

	/**
	 * Sets the value of the camaraComercio property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCamaraComercio(String value) {
		this.camaraComercio = value;
	}

	/**
	 * Gets the value of the razonSocialEstablecimiento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRazonSocialEstablecimiento() {
		return razonSocialEstablecimiento;
	}

	/**
	 * Sets the value of the razonSocialEstablecimiento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setRazonSocialEstablecimiento(String value) {
		this.razonSocialEstablecimiento = value;
	}

	/**
	 * Gets the value of the siglaEstablecimiento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSiglaEstablecimiento() {
		return siglaEstablecimiento;
	}

	/**
	 * Sets the value of the siglaEstablecimiento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSiglaEstablecimiento(String value) {
		this.siglaEstablecimiento = value;
	}

	/**
	 * Gets the value of the numeroMatricula property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumeroMatricula() {
		return numeroMatricula;
	}

	/**
	 * Sets the value of the numeroMatricula property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumeroMatricula(String value) {
		this.numeroMatricula = value;
	}

	/**
	 * Gets the value of the estadoMatricula property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEstadoMatricula() {
		return estadoMatricula;
	}

	/**
	 * Sets the value of the estadoMatricula property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEstadoMatricula(String value) {
		this.estadoMatricula = value;
	}

	/**
	 * Gets the value of the annoUltimaRenovacion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getAnnoUltimaRenovacion() {
		return annoUltimaRenovacion;
	}

	/**
	 * Sets the value of the annoUltimaRenovacion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setAnnoUltimaRenovacion(String value) {
		this.annoUltimaRenovacion = value;
	}

	/**
	 * Gets the value of the fechaMatricula property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFechaMatricula() {
		return fechaMatricula;
	}

	/**
	 * Sets the value of the fechaMatricula property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFechaMatricula(XMLGregorianCalendar value) {
		this.fechaMatricula = value;
	}

	/**
	 * Gets the value of the fechaCancelacion property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFechaCancelacion() {
		return fechaCancelacion;
	}

	/**
	 * Sets the value of the fechaCancelacion property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFechaCancelacion(XMLGregorianCalendar value) {
		this.fechaCancelacion = value;
	}

	/**
	 * Gets the value of the categoriaMatricula property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCategoriaMatricula() {
		return categoriaMatricula;
	}

	/**
	 * Sets the value of the categoriaMatricula property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCategoriaMatricula(String value) {
		this.categoriaMatricula = value;
	}

	/**
	 * Gets the value of the tipoSociedad property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTipoSociedad() {
		return tipoSociedad;
	}

	/**
	 * Sets the value of the tipoSociedad property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTipoSociedad(String value) {
		this.tipoSociedad = value;
	}

	/**
	 * Gets the value of the tipoOrganizacionEstablecimiento property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTipoOrganizacionEstablecimiento() {
		return tipoOrganizacionEstablecimiento;
	}

	/**
	 * Sets the value of the tipoOrganizacionEstablecimiento property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setTipoOrganizacionEstablecimiento(String value) {
		this.tipoOrganizacionEstablecimiento = value;
	}

	/**
	 * Gets the value of the numEmpleados property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNumEmpleados() {
		return numEmpleados;
	}

	/**
	 * Sets the value of the numEmpleados property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setNumEmpleados(String value) {
		this.numEmpleados = value;
	}

	/**
	 * Gets the value of the esAfiliado property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getEsAfiliado() {
		return esAfiliado;
	}

	/**
	 * Sets the value of the esAfiliado property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setEsAfiliado(String value) {
		this.esAfiliado = value;
	}

	/**
	 * Gets the value of the actividadEconomica property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the actividadEconomica property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getActividadEconomica().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link ActividadEconomica }
	 * 
	 * 
	 */
	public List<ActividadEconomica> getActividadEconomica() {
		if (actividadEconomica == null) {
			actividadEconomica = new ArrayList<ActividadEconomica>();
		}
		return this.actividadEconomica;
	}

	/**
	 * Gets the value of the representanteLegal property.
	 * 
	 * @return possible object is {@link RepresentanteLegal }
	 * 
	 */
	public RepresentanteLegal getRepresentanteLegal() {
		return representanteLegal;
	}

	/**
	 * Sets the value of the representanteLegal property.
	 * 
	 * @param value
	 *            allowed object is {@link RepresentanteLegal }
	 * 
	 */
	public void setRepresentanteLegal(RepresentanteLegal value) {
		this.representanteLegal = value;
	}

}
