//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for InformacionGeneralVehiculo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InformacionGeneralVehiculo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="marca" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linea" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modelo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="color" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroSerie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroMotor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroChasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroVin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cilindraje" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoCarroceria" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoCombustible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaMatriculaInicial" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="autoridadTransito" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="gravamenesPropiedad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clasicoAntiguo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="repotenciado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regrabacionMotor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroRegrabacionMotor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regrabacionChasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroRegrabacionChasis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regrabacionSerie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroRegrabacionSerie" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="regrabacionVin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroRegrabacionVin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vehiculoEnsenanza" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InformacionGeneralVehiculo", propOrder = {
    "marca",
    "linea",
    "modelo",
    "color",
    "numeroSerie",
    "numeroMotor",
    "numeroChasis",
    "numeroVin",
    "cilindraje",
    "tipoCarroceria",
    "tipoCombustible",
    "fechaMatriculaInicial",
    "autoridadTransito",
    "gravamenesPropiedad",
    "clasicoAntiguo",
    "repotenciado",
    "regrabacionMotor",
    "numeroRegrabacionMotor",
    "regrabacionChasis",
    "numeroRegrabacionChasis",
    "regrabacionSerie",
    "numeroRegrabacionSerie",
    "regrabacionVin",
    "numeroRegrabacionVin",
    "vehiculoEnsenanza"
})
public class InformacionGeneralVehiculo {

    protected String marca;
    protected String linea;
    protected String modelo;
    protected String color;
    protected String numeroSerie;
    protected String numeroMotor;
    protected String numeroChasis;
    protected String numeroVin;
    protected String cilindraje;
    protected String tipoCarroceria;
    protected String tipoCombustible;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaMatriculaInicial;
    protected String autoridadTransito;
    protected String gravamenesPropiedad;
    protected String clasicoAntiguo;
    protected String repotenciado;
    protected String regrabacionMotor;
    protected String numeroRegrabacionMotor;
    protected String regrabacionChasis;
    protected String numeroRegrabacionChasis;
    protected String regrabacionSerie;
    protected String numeroRegrabacionSerie;
    protected String regrabacionVin;
    protected String numeroRegrabacionVin;
    protected String vehiculoEnsenanza;

    /**
     * Gets the value of the marca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarca() {
        return marca;
    }

    /**
     * Sets the value of the marca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarca(String value) {
        this.marca = value;
    }

    /**
     * Gets the value of the linea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinea() {
        return linea;
    }

    /**
     * Sets the value of the linea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinea(String value) {
        this.linea = value;
    }

    /**
     * Gets the value of the modelo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelo() {
        return modelo;
    }

    /**
     * Sets the value of the modelo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelo(String value) {
        this.modelo = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColor(String value) {
        this.color = value;
    }

    /**
     * Gets the value of the numeroSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroSerie() {
        return numeroSerie;
    }

    /**
     * Sets the value of the numeroSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroSerie(String value) {
        this.numeroSerie = value;
    }

    /**
     * Gets the value of the numeroMotor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroMotor() {
        return numeroMotor;
    }

    /**
     * Sets the value of the numeroMotor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroMotor(String value) {
        this.numeroMotor = value;
    }

    /**
     * Gets the value of the numeroChasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroChasis() {
        return numeroChasis;
    }

    /**
     * Sets the value of the numeroChasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroChasis(String value) {
        this.numeroChasis = value;
    }

    /**
     * Gets the value of the numeroVin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroVin() {
        return numeroVin;
    }

    /**
     * Sets the value of the numeroVin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroVin(String value) {
        this.numeroVin = value;
    }

    /**
     * Gets the value of the cilindraje property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCilindraje() {
        return cilindraje;
    }

    /**
     * Sets the value of the cilindraje property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCilindraje(String value) {
        this.cilindraje = value;
    }

    /**
     * Gets the value of the tipoCarroceria property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCarroceria() {
        return tipoCarroceria;
    }

    /**
     * Sets the value of the tipoCarroceria property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCarroceria(String value) {
        this.tipoCarroceria = value;
    }

    /**
     * Gets the value of the tipoCombustible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCombustible() {
        return tipoCombustible;
    }

    /**
     * Sets the value of the tipoCombustible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCombustible(String value) {
        this.tipoCombustible = value;
    }

    /**
     * Gets the value of the fechaMatriculaInicial property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaMatriculaInicial() {
        return fechaMatriculaInicial;
    }

    /**
     * Sets the value of the fechaMatriculaInicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaMatriculaInicial(XMLGregorianCalendar value) {
        this.fechaMatriculaInicial = value;
    }

    /**
     * Gets the value of the autoridadTransito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoridadTransito() {
        return autoridadTransito;
    }

    /**
     * Sets the value of the autoridadTransito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoridadTransito(String value) {
        this.autoridadTransito = value;
    }

    /**
     * Gets the value of the gravamenesPropiedad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGravamenesPropiedad() {
        return gravamenesPropiedad;
    }

    /**
     * Sets the value of the gravamenesPropiedad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGravamenesPropiedad(String value) {
        this.gravamenesPropiedad = value;
    }

    /**
     * Gets the value of the clasicoAntiguo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClasicoAntiguo() {
        return clasicoAntiguo;
    }

    /**
     * Sets the value of the clasicoAntiguo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClasicoAntiguo(String value) {
        this.clasicoAntiguo = value;
    }

    /**
     * Gets the value of the repotenciado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepotenciado() {
        return repotenciado;
    }

    /**
     * Sets the value of the repotenciado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepotenciado(String value) {
        this.repotenciado = value;
    }

    /**
     * Gets the value of the regrabacionMotor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegrabacionMotor() {
        return regrabacionMotor;
    }

    /**
     * Sets the value of the regrabacionMotor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegrabacionMotor(String value) {
        this.regrabacionMotor = value;
    }

    /**
     * Gets the value of the numeroRegrabacionMotor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRegrabacionMotor() {
        return numeroRegrabacionMotor;
    }

    /**
     * Sets the value of the numeroRegrabacionMotor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRegrabacionMotor(String value) {
        this.numeroRegrabacionMotor = value;
    }

    /**
     * Gets the value of the regrabacionChasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegrabacionChasis() {
        return regrabacionChasis;
    }

    /**
     * Sets the value of the regrabacionChasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegrabacionChasis(String value) {
        this.regrabacionChasis = value;
    }

    /**
     * Gets the value of the numeroRegrabacionChasis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRegrabacionChasis() {
        return numeroRegrabacionChasis;
    }

    /**
     * Sets the value of the numeroRegrabacionChasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRegrabacionChasis(String value) {
        this.numeroRegrabacionChasis = value;
    }

    /**
     * Gets the value of the regrabacionSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegrabacionSerie() {
        return regrabacionSerie;
    }

    /**
     * Sets the value of the regrabacionSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegrabacionSerie(String value) {
        this.regrabacionSerie = value;
    }

    /**
     * Gets the value of the numeroRegrabacionSerie property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRegrabacionSerie() {
        return numeroRegrabacionSerie;
    }

    /**
     * Sets the value of the numeroRegrabacionSerie property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRegrabacionSerie(String value) {
        this.numeroRegrabacionSerie = value;
    }

    /**
     * Gets the value of the regrabacionVin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegrabacionVin() {
        return regrabacionVin;
    }

    /**
     * Sets the value of the regrabacionVin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegrabacionVin(String value) {
        this.regrabacionVin = value;
    }

    /**
     * Gets the value of the numeroRegrabacionVin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroRegrabacionVin() {
        return numeroRegrabacionVin;
    }

    /**
     * Sets the value of the numeroRegrabacionVin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroRegrabacionVin(String value) {
        this.numeroRegrabacionVin = value;
    }

    /**
     * Gets the value of the vehiculoEnsenanza property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehiculoEnsenanza() {
        return vehiculoEnsenanza;
    }

    /**
     * Sets the value of the vehiculoEnsenanza property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehiculoEnsenanza(String value) {
        this.vehiculoEnsenanza = value;
    }

}
