//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InfraccionesTransito complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InfraccionesTransito">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exitoso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suspensionLicencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="infraccion" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Infraccion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="comparendo" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Comparendo" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="acuerdoPago" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}AcuerdoPago" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InfraccionesTransito", propOrder = {
    "exitoso",
    "suspensionLicencia",
    "infraccion",
    "comparendo",
    "acuerdoPago"
})
public class InfraccionesTransito {

    protected String exitoso;
    protected String suspensionLicencia;
    protected List<Infraccion> infraccion;
    protected List<Comparendo> comparendo;
    protected List<AcuerdoPago> acuerdoPago;

    /**
     * Gets the value of the exitoso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExitoso() {
        return exitoso;
    }

    /**
     * Sets the value of the exitoso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExitoso(String value) {
        this.exitoso = value;
    }

    /**
     * Gets the value of the suspensionLicencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuspensionLicencia() {
        return suspensionLicencia;
    }

    /**
     * Sets the value of the suspensionLicencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuspensionLicencia(String value) {
        this.suspensionLicencia = value;
    }

    /**
     * Gets the value of the infraccion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the infraccion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInfraccion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Infraccion }
     * 
     * 
     */
    public List<Infraccion> getInfraccion() {
        if (infraccion == null) {
            infraccion = new ArrayList<Infraccion>();
        }
        return this.infraccion;
    }

    /**
     * Gets the value of the comparendo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comparendo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComparendo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comparendo }
     * 
     * 
     */
    public List<Comparendo> getComparendo() {
        if (comparendo == null) {
            comparendo = new ArrayList<Comparendo>();
        }
        return this.comparendo;
    }

    /**
     * Gets the value of the acuerdoPago property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the acuerdoPago property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAcuerdoPago().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AcuerdoPago }
     * 
     * 
     */
    public List<AcuerdoPago> getAcuerdoPago() {
        if (acuerdoPago == null) {
            acuerdoPago = new ArrayList<AcuerdoPago>();
        }
        return this.acuerdoPago;
    }

}
