//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LicenciaConduccion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LicenciaConduccion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroLicencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="organismoTransitoExpide" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaExpedicion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="estadoLicencia" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="restricciones" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="detalleLicencia" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}DetalleLicencia" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LicenciaConduccion", propOrder = {
    "numeroLicencia",
    "organismoTransitoExpide",
    "fechaExpedicion",
    "estadoLicencia",
    "restricciones",
    "detalleLicencia"
})
public class LicenciaConduccion {

    protected String numeroLicencia;
    protected String organismoTransitoExpide;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaExpedicion;
    protected String estadoLicencia;
    protected String restricciones;
    protected List<DetalleLicencia> detalleLicencia;

    /**
     * Gets the value of the numeroLicencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroLicencia() {
        return numeroLicencia;
    }

    /**
     * Sets the value of the numeroLicencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroLicencia(String value) {
        this.numeroLicencia = value;
    }

    /**
     * Gets the value of the organismoTransitoExpide property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrganismoTransitoExpide() {
        return organismoTransitoExpide;
    }

    /**
     * Sets the value of the organismoTransitoExpide property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrganismoTransitoExpide(String value) {
        this.organismoTransitoExpide = value;
    }

    /**
     * Gets the value of the fechaExpedicion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaExpedicion() {
        return fechaExpedicion;
    }

    /**
     * Sets the value of the fechaExpedicion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaExpedicion(XMLGregorianCalendar value) {
        this.fechaExpedicion = value;
    }

    /**
     * Gets the value of the estadoLicencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoLicencia() {
        return estadoLicencia;
    }

    /**
     * Sets the value of the estadoLicencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoLicencia(String value) {
        this.estadoLicencia = value;
    }

    /**
     * Gets the value of the restricciones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRestricciones() {
        return restricciones;
    }

    /**
     * Sets the value of the restricciones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRestricciones(String value) {
        this.restricciones = value;
    }

    /**
     * Gets the value of the detalleLicencia property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the detalleLicencia property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDetalleLicencia().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DetalleLicencia }
     * 
     * 
     */
    public List<DetalleLicencia> getDetalleLicencia() {
        if (detalleLicencia == null) {
            detalleLicencia = new ArrayList<DetalleLicencia>();
        }
        return this.detalleLicencia;
    }

}
