//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ConsultarFuentesExternasResponse_QNAME = new QName("http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", "consultarFuentesExternasResponse");
    private final static QName _SystemException_QNAME = new QName("http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", "systemException");
    private final static QName _ConsultarFuentesExternas_QNAME = new QName("http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", "consultarFuentesExternas");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemException }
     * 
     */
    public SystemException createSystemException() {
        return new SystemException();
    }

    /**
     * Create an instance of {@link ConsultarFuentesExternasResponse }
     * 
     */
    public ConsultarFuentesExternasResponse createConsultarFuentesExternasResponse() {
        return new ConsultarFuentesExternasResponse();
    }

    /**
     * Create an instance of {@link ConsultarFuentesExternas }
     * 
     */
    public ConsultarFuentesExternas createConsultarFuentesExternas() {
        return new ConsultarFuentesExternas();
    }

    /**
     * Create an instance of {@link Solicitud }
     * 
     */
    public Solicitud createSolicitud() {
        return new Solicitud();
    }

    /**
     * Create an instance of {@link Periodos }
     * 
     */
    public Periodos createPeriodos() {
        return new Periodos();
    }

    /**
     * Create an instance of {@link Cesantias }
     * 
     */
    public Cesantias createCesantias() {
        return new Cesantias();
    }

    /**
     * Create an instance of {@link Afiliacion }
     * 
     */
    public Afiliacion createAfiliacion() {
        return new Afiliacion();
    }

    /**
     * Create an instance of {@link AsistenciaSocial }
     * 
     */
    public AsistenciaSocial createAsistenciaSocial() {
        return new AsistenciaSocial();
    }

    /**
     * Create an instance of {@link Persona }
     * 
     */
    public Persona createPersona() {
        return new Persona();
    }

    /**
     * Create an instance of {@link LimitacionesPropiedad }
     * 
     */
    public LimitacionesPropiedad createLimitacionesPropiedad() {
        return new LimitacionesPropiedad();
    }

    /**
     * Create an instance of {@link Cpnt }
     * 
     */
    public Cpnt createCpnt() {
        return new Cpnt();
    }

    /**
     * Create an instance of {@link ConsejoProfesional }
     * 
     */
    public ConsejoProfesional createConsejoProfesional() {
        return new ConsejoProfesional();
    }

    /**
     * Create an instance of {@link Comparendo }
     * 
     */
    public Comparendo createComparendo() {
        return new Comparendo();
    }

    /**
     * Create an instance of {@link PuestoVotacion }
     * 
     */
    public PuestoVotacion createPuestoVotacion() {
        return new PuestoVotacion();
    }

    /**
     * Create an instance of {@link RuntPlaca }
     * 
     */
    public RuntPlaca createRuntPlaca() {
        return new RuntPlaca();
    }

    /**
     * Create an instance of {@link AfiliadosCompensados }
     * 
     */
    public AfiliadosCompensados createAfiliadosCompensados() {
        return new AfiliadosCompensados();
    }

    /**
     * Create an instance of {@link DianRut }
     * 
     */
    public DianRut createDianRut() {
        return new DianRut();
    }

    /**
     * Create an instance of {@link CertificadoTecnicoMecanicoGases }
     * 
     */
    public CertificadoTecnicoMecanicoGases createCertificadoTecnicoMecanicoGases() {
        return new CertificadoTecnicoMecanicoGases();
    }

    /**
     * Create an instance of {@link Copnia }
     * 
     */
    public Copnia createCopnia() {
        return new Copnia();
    }

    /**
     * Create an instance of {@link DetalleLicencia }
     * 
     */
    public DetalleLicencia createDetalleLicencia() {
        return new DetalleLicencia();
    }

    /**
     * Create an instance of {@link AcuerdoPago }
     * 
     */
    public AcuerdoPago createAcuerdoPago() {
        return new AcuerdoPago();
    }

    /**
     * Create an instance of {@link Anec }
     * 
     */
    public Anec createAnec() {
        return new Anec();
    }

    /**
     * Create an instance of {@link Pension }
     * 
     */
    public Pension createPension() {
        return new Pension();
    }

    /**
     * Create an instance of {@link PolizaSoat }
     * 
     */
    public PolizaSoat createPolizaSoat() {
        return new PolizaSoat();
    }

    /**
     * Create an instance of {@link Asopagos }
     * 
     */
    public Asopagos createAsopagos() {
        return new Asopagos();
    }

    /**
     * Create an instance of {@link Pensionado }
     * 
     */
    public Pensionado createPensionado() {
        return new Pensionado();
    }

    /**
     * Create an instance of {@link Identificacion }
     * 
     */
    public Identificacion createIdentificacion() {
        return new Identificacion();
    }

    /**
     * Create an instance of {@link Camara }
     * 
     */
    public Camara createCamara() {
        return new Camara();
    }

    /**
     * Create an instance of {@link InfraccionesTransito }
     * 
     */
    public InfraccionesTransito createInfraccionesTransito() {
        return new InfraccionesTransito();
    }

    /**
     * Create an instance of {@link Contraloria }
     * 
     */
    public Contraloria createContraloria() {
        return new Contraloria();
    }

    /**
     * Create an instance of {@link Ruaf }
     * 
     */
    public Ruaf createRuaf() {
        return new Ruaf();
    }

    /**
     * Create an instance of {@link Afiliado }
     * 
     */
    public Afiliado createAfiliado() {
        return new Afiliado();
    }

    /**
     * Create an instance of {@link Salud }
     * 
     */
    public Salud createSalud() {
        return new Salud();
    }

    /**
     * Create an instance of {@link CompensacionFamiliar }
     * 
     */
    public CompensacionFamiliar createCompensacionFamiliar() {
        return new CompensacionFamiliar();
    }

    /**
     * Create an instance of {@link TramiteCedula }
     * 
     */
    public TramiteCedula createTramiteCedula() {
        return new TramiteCedula();
    }

    /**
     * Create an instance of {@link DatosTecnicosVehiculo }
     * 
     */
    public DatosTecnicosVehiculo createDatosTecnicosVehiculo() {
        return new DatosTecnicosVehiculo();
    }

    /**
     * Create an instance of {@link Icetex }
     * 
     */
    public Icetex createIcetex() {
        return new Icetex();
    }

    /**
     * Create an instance of {@link RuesCamaras }
     * 
     */
    public RuesCamaras createRuesCamaras() {
        return new RuesCamaras();
    }

    /**
     * Create an instance of {@link Cpnaa }
     * 
     */
    public Cpnaa createCpnaa() {
        return new Cpnaa();
    }

    /**
     * Create an instance of {@link LicenciaConduccion }
     * 
     */
    public LicenciaConduccion createLicenciaConduccion() {
        return new LicenciaConduccion();
    }

    /**
     * Create an instance of {@link SisbenPuntaje }
     * 
     */
    public SisbenPuntaje createSisbenPuntaje() {
        return new SisbenPuntaje();
    }

    /**
     * Create an instance of {@link RamaJudicial }
     * 
     */
    public RamaJudicial createRamaJudicial() {
        return new RamaJudicial();
    }

    /**
     * Create an instance of {@link Administradora }
     * 
     */
    public Administradora createAdministradora() {
        return new Administradora();
    }

    /**
     * Create an instance of {@link CertificadoConduccion }
     * 
     */
    public CertificadoConduccion createCertificadoConduccion() {
        return new CertificadoConduccion();
    }

    /**
     * Create an instance of {@link Runt }
     * 
     */
    public Runt createRunt() {
        return new Runt();
    }

    /**
     * Create an instance of {@link Procuraduria }
     * 
     */
    public Procuraduria createProcuraduria() {
        return new Procuraduria();
    }

    /**
     * Create an instance of {@link Bdua }
     * 
     */
    public Bdua createBdua() {
        return new Bdua();
    }

    /**
     * Create an instance of {@link ActividadEconomica }
     * 
     */
    public ActividadEconomica createActividadEconomica() {
        return new ActividadEconomica();
    }

    /**
     * Create an instance of {@link InformacionGeneralVehiculo }
     * 
     */
    public InformacionGeneralVehiculo createInformacionGeneralVehiculo() {
        return new InformacionGeneralVehiculo();
    }

    /**
     * Create an instance of {@link Cpae }
     * 
     */
    public Cpae createCpae() {
        return new Cpae();
    }

    /**
     * Create an instance of {@link RepresentanteLegal }
     * 
     */
    public RepresentanteLegal createRepresentanteLegal() {
        return new RepresentanteLegal();
    }

    /**
     * Create an instance of {@link Cpip }
     * 
     */
    public Cpip createCpip() {
        return new Cpip();
    }

    /**
     * Create an instance of {@link RiesgosProfesionales }
     * 
     */
    public RiesgosProfesionales createRiesgosProfesionales() {
        return new RiesgosProfesionales();
    }

    /**
     * Create an instance of {@link Credito }
     * 
     */
    public Credito createCredito() {
        return new Credito();
    }

    /**
     * Create an instance of {@link Infraccion }
     * 
     */
    public Infraccion createInfraccion() {
        return new Infraccion();
    }

    /**
     * Create an instance of {@link Resolucion }
     * 
     */
    public Resolucion createResolucion() {
        return new Resolucion();
    }

    /**
     * Create an instance of {@link Ubicacion }
     * 
     */
    public Ubicacion createUbicacion() {
        return new Ubicacion();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarFuentesExternasResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", name = "consultarFuentesExternasResponse")
    public JAXBElement<ConsultarFuentesExternasResponse> createConsultarFuentesExternasResponse(ConsultarFuentesExternasResponse value) {
        return new JAXBElement<ConsultarFuentesExternasResponse>(_ConsultarFuentesExternasResponse_QNAME, ConsultarFuentesExternasResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SystemException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", name = "systemException")
    public JAXBElement<SystemException> createSystemException(SystemException value) {
        return new JAXBElement<SystemException>(_SystemException_QNAME, SystemException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConsultarFuentesExternas }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0", name = "consultarFuentesExternas")
    public JAXBElement<ConsultarFuentesExternas> createConsultarFuentesExternas(ConsultarFuentesExternas value) {
        return new JAXBElement<ConsultarFuentesExternas>(_ConsultarFuentesExternas_QNAME, ConsultarFuentesExternas.class, null, value);
    }

}
