//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Pensionado complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pensionado">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroResolucionPension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pensionCompartida" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estadoPension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoPension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoPensionado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pagador" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaResolucion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="modalidadPension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pensionado", propOrder = {
    "numeroResolucionPension",
    "pensionCompartida",
    "estadoPension",
    "tipoPension",
    "tipoPensionado",
    "pagador",
    "fechaResolucion",
    "modalidadPension"
})
public class Pensionado {

    protected String numeroResolucionPension;
    protected String pensionCompartida;
    protected String estadoPension;
    protected String tipoPension;
    protected String tipoPensionado;
    protected String pagador;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaResolucion;
    protected String modalidadPension;

    /**
     * Gets the value of the numeroResolucionPension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroResolucionPension() {
        return numeroResolucionPension;
    }

    /**
     * Sets the value of the numeroResolucionPension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroResolucionPension(String value) {
        this.numeroResolucionPension = value;
    }

    /**
     * Gets the value of the pensionCompartida property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPensionCompartida() {
        return pensionCompartida;
    }

    /**
     * Sets the value of the pensionCompartida property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPensionCompartida(String value) {
        this.pensionCompartida = value;
    }

    /**
     * Gets the value of the estadoPension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoPension() {
        return estadoPension;
    }

    /**
     * Sets the value of the estadoPension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoPension(String value) {
        this.estadoPension = value;
    }

    /**
     * Gets the value of the tipoPension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPension() {
        return tipoPension;
    }

    /**
     * Sets the value of the tipoPension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPension(String value) {
        this.tipoPension = value;
    }

    /**
     * Gets the value of the tipoPensionado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoPensionado() {
        return tipoPensionado;
    }

    /**
     * Sets the value of the tipoPensionado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoPensionado(String value) {
        this.tipoPensionado = value;
    }

    /**
     * Gets the value of the pagador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPagador() {
        return pagador;
    }

    /**
     * Sets the value of the pagador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPagador(String value) {
        this.pagador = value;
    }

    /**
     * Gets the value of the fechaResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaResolucion() {
        return fechaResolucion;
    }

    /**
     * Sets the value of the fechaResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaResolucion(XMLGregorianCalendar value) {
        this.fechaResolucion = value;
    }

    /**
     * Gets the value of the modalidadPension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModalidadPension() {
        return modalidadPension;
    }

    /**
     * Sets the value of the modalidadPension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModalidadPension(String value) {
        this.modalidadPension = value;
    }

}
