//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Periodos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Periodos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="eps_eoc" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="periodosCompensados" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaAfiliacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="diasCompensados" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoAfiliado" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="norma" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Periodos", propOrder = {
    "epsEoc",
    "periodosCompensados",
    "fechaAfiliacion",
    "diasCompensados",
    "tipoAfiliado",
    "norma"
})
public class Periodos {

    @XmlElement(name = "eps_eoc")
    protected String epsEoc;
    @XmlElement(name = "periodosCompensados", type = String.class)
    protected String periodosCompensados;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaAfiliacion;
    protected String diasCompensados;
    protected String tipoAfiliado;
    protected String norma;

    /**
     * Gets the value of the epsEoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEpsEoc() {
        return epsEoc;
    }

    /**
     * Sets the value of the epsEoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEpsEoc(String value) {
        this.epsEoc = value;
    }

    /**
     * Gets the value of the periodosCompensados property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodosCompensados() {
        return periodosCompensados;
    }

    /**
     * Sets the value of the periodosCompensados property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodosCompensados(String value) {
        this.periodosCompensados = value;
    }

    /**
     * Gets the value of the fechaAfiliacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaAfiliacion() {
        return fechaAfiliacion;
    }

    /**
     * Sets the value of the fechaAfiliacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaAfiliacion(XMLGregorianCalendar value) {
        this.fechaAfiliacion = value;
    }

    /**
     * Gets the value of the diasCompensados property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiasCompensados() {
        return diasCompensados;
    }

    /**
     * Sets the value of the diasCompensados property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiasCompensados(String value) {
        this.diasCompensados = value;
    }

    /**
     * Gets the value of the tipoAfiliado property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAfiliado() {
        return tipoAfiliado;
    }

    /**
     * Sets the value of the tipoAfiliado property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAfiliado(String value) {
        this.tipoAfiliado = value;
    }

    /**
     * Gets the value of the norma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNorma() {
        return norma;
    }

    /**
     * Sets the value of the norma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNorma(String value) {
        this.norma = value;
    }

}
