//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//

package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for RuesCamaras complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RuesCamaras">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="exitoso" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="detalleCamara" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Camara" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RuesCamaras", propOrder = { "exitoso", "detalleCamara" })
public class RuesCamaras {

	protected String exitoso;
    protected List<Camara> detalleCamara;

	/**
	 * Gets the value of the exitoso property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getExitoso() {
		return exitoso;
	}

	/**
	 * Sets the value of the exitoso property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setExitoso(String value) {
		this.exitoso = value;
	}

	/**
	 * Gets the value of the detalleCamara property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a snapshot.
	 * Therefore any modification you make to the returned list will be present
	 * inside the JAXB object. This is why there is not a <CODE>set</CODE> method
	 * for the detalleCamara property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDetalleCamara().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link Camara }
	 * 
	 * 
	 */
	public List<Camara> getDetalleCamara() {
		if (detalleCamara == null) {
			detalleCamara = new ArrayList<Camara>();
		}
		return this.detalleCamara;
	}

}
