//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AcuerdoPago complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AcuerdoPago">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fechaResolucion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="permitePago" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="comparendo" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Comparendo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AcuerdoPago", propOrder = {
    "fechaResolucion",
    "permitePago",
    "comparendo"
})
public class AcuerdoPago {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaResolucion;
    protected String permitePago;
    protected Comparendo comparendo;

    /**
     * Gets the value of the fechaResolucion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaResolucion() {
        return fechaResolucion;
    }

    /**
     * Sets the value of the fechaResolucion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaResolucion(XMLGregorianCalendar value) {
        this.fechaResolucion = value;
    }

    /**
     * Gets the value of the permitePago property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPermitePago() {
        return permitePago;
    }

    /**
     * Sets the value of the permitePago property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPermitePago(String value) {
        this.permitePago = value;
    }

    /**
     * Gets the value of the comparendo property.
     * 
     * @return
     *     possible object is
     *     {@link Comparendo }
     *     
     */
    public Comparendo getComparendo() {
        return comparendo;
    }

    /**
     * Sets the value of the comparendo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comparendo }
     *     
     */
    public void setComparendo(Comparendo value) {
        this.comparendo = value;
    }

}
