//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AsistenciaSocial complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AsistenciaSocial">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fechaEntregaUltBeneficio" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="ubicacionEntregaBeneficio" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Ubicacion" minOccurs="0"/>
 *         &lt;element name="valorBeneficio" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="tipoSubsidio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="estadoBeneficio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tipoBeneficio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="administradora" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="programa" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaVinculacion" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="estadoVinculacion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AsistenciaSocial", propOrder = {
    "fechaEntregaUltBeneficio",
    "ubicacionEntregaBeneficio",
    "valorBeneficio",
    "tipoSubsidio",
    "estadoBeneficio",
    "tipoBeneficio",
    "administradora",
    "programa",
    "fechaVinculacion",
    "estadoVinculacion"
})
public class AsistenciaSocial {

    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaEntregaUltBeneficio;
    protected Ubicacion ubicacionEntregaBeneficio;
    protected Double valorBeneficio;
    protected String tipoSubsidio;
    protected String estadoBeneficio;
    protected String tipoBeneficio;
    protected String administradora;
    protected String programa;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaVinculacion;
    protected String estadoVinculacion;

    /**
     * Gets the value of the fechaEntregaUltBeneficio property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaEntregaUltBeneficio() {
        return fechaEntregaUltBeneficio;
    }

    /**
     * Sets the value of the fechaEntregaUltBeneficio property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaEntregaUltBeneficio(XMLGregorianCalendar value) {
        this.fechaEntregaUltBeneficio = value;
    }

    /**
     * Gets the value of the ubicacionEntregaBeneficio property.
     * 
     * @return
     *     possible object is
     *     {@link Ubicacion }
     *     
     */
    public Ubicacion getUbicacionEntregaBeneficio() {
        return ubicacionEntregaBeneficio;
    }

    /**
     * Sets the value of the ubicacionEntregaBeneficio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ubicacion }
     *     
     */
    public void setUbicacionEntregaBeneficio(Ubicacion value) {
        this.ubicacionEntregaBeneficio = value;
    }

    /**
     * Gets the value of the valorBeneficio property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValorBeneficio() {
        return valorBeneficio;
    }

    /**
     * Sets the value of the valorBeneficio property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValorBeneficio(Double value) {
        this.valorBeneficio = value;
    }

    /**
     * Gets the value of the tipoSubsidio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoSubsidio() {
        return tipoSubsidio;
    }

    /**
     * Sets the value of the tipoSubsidio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoSubsidio(String value) {
        this.tipoSubsidio = value;
    }

    /**
     * Gets the value of the estadoBeneficio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoBeneficio() {
        return estadoBeneficio;
    }

    /**
     * Sets the value of the estadoBeneficio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoBeneficio(String value) {
        this.estadoBeneficio = value;
    }

    /**
     * Gets the value of the tipoBeneficio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoBeneficio() {
        return tipoBeneficio;
    }

    /**
     * Sets the value of the tipoBeneficio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoBeneficio(String value) {
        this.tipoBeneficio = value;
    }

    /**
     * Gets the value of the administradora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministradora() {
        return administradora;
    }

    /**
     * Sets the value of the administradora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministradora(String value) {
        this.administradora = value;
    }

    /**
     * Gets the value of the programa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrograma() {
        return programa;
    }

    /**
     * Sets the value of the programa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrograma(String value) {
        this.programa = value;
    }

    /**
     * Gets the value of the fechaVinculacion property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaVinculacion() {
        return fechaVinculacion;
    }

    /**
     * Sets the value of the fechaVinculacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaVinculacion(XMLGregorianCalendar value) {
        this.fechaVinculacion = value;
    }

    /**
     * Gets the value of the estadoVinculacion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEstadoVinculacion() {
        return estadoVinculacion;
    }

    /**
     * Sets the value of the estadoVinculacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEstadoVinculacion(String value) {
        this.estadoVinculacion = value;
    }

}
