//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConsultarFuentesExternasResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConsultarFuentesExternasResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bdua" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Bdua" minOccurs="0"/>
 *         &lt;element name="ruaf" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Ruaf" minOccurs="0"/>
 *         &lt;element name="nombreCompleto" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Persona" minOccurs="0"/>
 *         &lt;element name="procuraduria" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Procuraduria" minOccurs="0"/>
 *         &lt;element name="sisbenPuntaje" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}SisbenPuntaje" minOccurs="0"/>
 *         &lt;element name="dianRut" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}DianRut" minOccurs="0"/>
 *         &lt;element name="puestoVotacion" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}PuestoVotacion" minOccurs="0"/>
 *         &lt;element name="contraloria" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Contraloria" minOccurs="0"/>
 *         &lt;element name="copnia" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Copnia" minOccurs="0"/>
 *         &lt;element name="asopagos" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Asopagos" minOccurs="0"/>
 *         &lt;element name="ramaJudicial" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}RamaJudicial" minOccurs="0"/>
 *         &lt;element name="tramiteCedula" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}TramiteCedula" minOccurs="0"/>
 *         &lt;element name="infraccionesTransitoSimit" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}InfraccionesTransito" minOccurs="0"/>
 *         &lt;element name="cpae" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Cpae" minOccurs="0"/>
 *         &lt;element name="consejoProfesional" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}ConsejoProfesional" minOccurs="0"/>
 *         &lt;element name="cpnaa" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Cpnaa" minOccurs="0"/>
 *         &lt;element name="anec" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Anec" minOccurs="0"/>
 *         &lt;element name="cpip" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Cpip" minOccurs="0"/>
 *         &lt;element name="icetex" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Icetex" minOccurs="0"/>
 *         &lt;element name="cpnt" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Cpnt" minOccurs="0"/>
 *         &lt;element name="ruesCamaras" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}RuesCamaras" minOccurs="0"/>
 *         &lt;element name="runt" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Runt" minOccurs="0"/>
 *         &lt;element name="runtPlaca" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}RuntPlaca" minOccurs="0"/>
 *         &lt;element name="afiliadosCompensados" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}AfiliadosCompensados" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConsultarFuentesExternasResponse", propOrder = {
    "bdua",
    "ruaf",
    "nombreCompleto",
    "procuraduria",
    "sisbenPuntaje",
    "dianRut",
    "puestoVotacion",
    "contraloria",
    "copnia",
    "asopagos",
    "ramaJudicial",
    "tramiteCedula",
    "infraccionesTransitoSimit",
    "cpae",
    "consejoProfesional",
    "cpnaa",
    "anec",
    "cpip",
    "icetex",
    "cpnt",
    "ruesCamaras",
    "runt",
    "runtPlaca",
    "afiliadosCompensados"
})
public class ConsultarFuentesExternasResponse {

    protected Bdua bdua;
    protected Ruaf ruaf;
    protected Persona nombreCompleto;
    protected Procuraduria procuraduria;
    protected SisbenPuntaje sisbenPuntaje;
    protected DianRut dianRut;
    protected PuestoVotacion puestoVotacion;
    protected Contraloria contraloria;
    protected Copnia copnia;
    protected Asopagos asopagos;
    protected RamaJudicial ramaJudicial;
    protected TramiteCedula tramiteCedula;
    protected InfraccionesTransito infraccionesTransitoSimit;
    protected Cpae cpae;
    protected ConsejoProfesional consejoProfesional;
    protected Cpnaa cpnaa;
    protected Anec anec;
    protected Cpip cpip;
    protected Icetex icetex;
    protected Cpnt cpnt;
    protected RuesCamaras ruesCamaras;
    protected Runt runt;
    protected RuntPlaca runtPlaca;
    protected AfiliadosCompensados afiliadosCompensados;

    /**
     * Gets the value of the bdua property.
     * 
     * @return
     *     possible object is
     *     {@link Bdua }
     *     
     */
    public Bdua getBdua() {
        return bdua;
    }

    /**
     * Sets the value of the bdua property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bdua }
     *     
     */
    public void setBdua(Bdua value) {
        this.bdua = value;
    }

    /**
     * Gets the value of the ruaf property.
     * 
     * @return
     *     possible object is
     *     {@link Ruaf }
     *     
     */
    public Ruaf getRuaf() {
        return ruaf;
    }

    /**
     * Sets the value of the ruaf property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ruaf }
     *     
     */
    public void setRuaf(Ruaf value) {
        this.ruaf = value;
    }

    /**
     * Gets the value of the nombreCompleto property.
     * 
     * @return
     *     possible object is
     *     {@link Persona }
     *     
     */
    public Persona getNombreCompleto() {
        return nombreCompleto;
    }

    /**
     * Sets the value of the nombreCompleto property.
     * 
     * @param value
     *     allowed object is
     *     {@link Persona }
     *     
     */
    public void setNombreCompleto(Persona value) {
        this.nombreCompleto = value;
    }

    /**
     * Gets the value of the procuraduria property.
     * 
     * @return
     *     possible object is
     *     {@link Procuraduria }
     *     
     */
    public Procuraduria getProcuraduria() {
        return procuraduria;
    }

    /**
     * Sets the value of the procuraduria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Procuraduria }
     *     
     */
    public void setProcuraduria(Procuraduria value) {
        this.procuraduria = value;
    }

    /**
     * Gets the value of the sisbenPuntaje property.
     * 
     * @return
     *     possible object is
     *     {@link SisbenPuntaje }
     *     
     */
    public SisbenPuntaje getSisbenPuntaje() {
        return sisbenPuntaje;
    }

    /**
     * Sets the value of the sisbenPuntaje property.
     * 
     * @param value
     *     allowed object is
     *     {@link SisbenPuntaje }
     *     
     */
    public void setSisbenPuntaje(SisbenPuntaje value) {
        this.sisbenPuntaje = value;
    }

    /**
     * Gets the value of the dianRut property.
     * 
     * @return
     *     possible object is
     *     {@link DianRut }
     *     
     */
    public DianRut getDianRut() {
        return dianRut;
    }

    /**
     * Sets the value of the dianRut property.
     * 
     * @param value
     *     allowed object is
     *     {@link DianRut }
     *     
     */
    public void setDianRut(DianRut value) {
        this.dianRut = value;
    }

    /**
     * Gets the value of the puestoVotacion property.
     * 
     * @return
     *     possible object is
     *     {@link PuestoVotacion }
     *     
     */
    public PuestoVotacion getPuestoVotacion() {
        return puestoVotacion;
    }

    /**
     * Sets the value of the puestoVotacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link PuestoVotacion }
     *     
     */
    public void setPuestoVotacion(PuestoVotacion value) {
        this.puestoVotacion = value;
    }

    /**
     * Gets the value of the contraloria property.
     * 
     * @return
     *     possible object is
     *     {@link Contraloria }
     *     
     */
    public Contraloria getContraloria() {
        return contraloria;
    }

    /**
     * Sets the value of the contraloria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Contraloria }
     *     
     */
    public void setContraloria(Contraloria value) {
        this.contraloria = value;
    }

    /**
     * Gets the value of the copnia property.
     * 
     * @return
     *     possible object is
     *     {@link Copnia }
     *     
     */
    public Copnia getCopnia() {
        return copnia;
    }

    /**
     * Sets the value of the copnia property.
     * 
     * @param value
     *     allowed object is
     *     {@link Copnia }
     *     
     */
    public void setCopnia(Copnia value) {
        this.copnia = value;
    }

    /**
     * Gets the value of the asopagos property.
     * 
     * @return
     *     possible object is
     *     {@link Asopagos }
     *     
     */
    public Asopagos getAsopagos() {
        return asopagos;
    }

    /**
     * Sets the value of the asopagos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Asopagos }
     *     
     */
    public void setAsopagos(Asopagos value) {
        this.asopagos = value;
    }

    /**
     * Gets the value of the ramaJudicial property.
     * 
     * @return
     *     possible object is
     *     {@link RamaJudicial }
     *     
     */
    public RamaJudicial getRamaJudicial() {
        return ramaJudicial;
    }

    /**
     * Sets the value of the ramaJudicial property.
     * 
     * @param value
     *     allowed object is
     *     {@link RamaJudicial }
     *     
     */
    public void setRamaJudicial(RamaJudicial value) {
        this.ramaJudicial = value;
    }

    /**
     * Gets the value of the tramiteCedula property.
     * 
     * @return
     *     possible object is
     *     {@link TramiteCedula }
     *     
     */
    public TramiteCedula getTramiteCedula() {
        return tramiteCedula;
    }

    /**
     * Sets the value of the tramiteCedula property.
     * 
     * @param value
     *     allowed object is
     *     {@link TramiteCedula }
     *     
     */
    public void setTramiteCedula(TramiteCedula value) {
        this.tramiteCedula = value;
    }

    /**
     * Gets the value of the infraccionesTransitoSimit property.
     * 
     * @return
     *     possible object is
     *     {@link InfraccionesTransito }
     *     
     */
    public InfraccionesTransito getInfraccionesTransitoSimit() {
        return infraccionesTransitoSimit;
    }

    /**
     * Sets the value of the infraccionesTransitoSimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfraccionesTransito }
     *     
     */
    public void setInfraccionesTransitoSimit(InfraccionesTransito value) {
        this.infraccionesTransitoSimit = value;
    }

    /**
     * Gets the value of the cpae property.
     * 
     * @return
     *     possible object is
     *     {@link Cpae }
     *     
     */
    public Cpae getCpae() {
        return cpae;
    }

    /**
     * Sets the value of the cpae property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpae }
     *     
     */
    public void setCpae(Cpae value) {
        this.cpae = value;
    }

    /**
     * Gets the value of the consejoProfesional property.
     * 
     * @return
     *     possible object is
     *     {@link ConsejoProfesional }
     *     
     */
    public ConsejoProfesional getConsejoProfesional() {
        return consejoProfesional;
    }

    /**
     * Sets the value of the consejoProfesional property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConsejoProfesional }
     *     
     */
    public void setConsejoProfesional(ConsejoProfesional value) {
        this.consejoProfesional = value;
    }

    /**
     * Gets the value of the cpnaa property.
     * 
     * @return
     *     possible object is
     *     {@link Cpnaa }
     *     
     */
    public Cpnaa getCpnaa() {
        return cpnaa;
    }

    /**
     * Sets the value of the cpnaa property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpnaa }
     *     
     */
    public void setCpnaa(Cpnaa value) {
        this.cpnaa = value;
    }

    /**
     * Gets the value of the anec property.
     * 
     * @return
     *     possible object is
     *     {@link Anec }
     *     
     */
    public Anec getAnec() {
        return anec;
    }

    /**
     * Sets the value of the anec property.
     * 
     * @param value
     *     allowed object is
     *     {@link Anec }
     *     
     */
    public void setAnec(Anec value) {
        this.anec = value;
    }

    /**
     * Gets the value of the cpip property.
     * 
     * @return
     *     possible object is
     *     {@link Cpip }
     *     
     */
    public Cpip getCpip() {
        return cpip;
    }

    /**
     * Sets the value of the cpip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpip }
     *     
     */
    public void setCpip(Cpip value) {
        this.cpip = value;
    }

    /**
     * Gets the value of the icetex property.
     * 
     * @return
     *     possible object is
     *     {@link Icetex }
     *     
     */
    public Icetex getIcetex() {
        return icetex;
    }

    /**
     * Sets the value of the icetex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Icetex }
     *     
     */
    public void setIcetex(Icetex value) {
        this.icetex = value;
    }

    /**
     * Gets the value of the cpnt property.
     * 
     * @return
     *     possible object is
     *     {@link Cpnt }
     *     
     */
    public Cpnt getCpnt() {
        return cpnt;
    }

    /**
     * Sets the value of the cpnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cpnt }
     *     
     */
    public void setCpnt(Cpnt value) {
        this.cpnt = value;
    }

    /**
     * Gets the value of the ruesCamaras property.
     * 
     * @return
     *     possible object is
     *     {@link RuesCamaras }
     *     
     */
    public RuesCamaras getRuesCamaras() {
        return ruesCamaras;
    }

    /**
     * Sets the value of the ruesCamaras property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuesCamaras }
     *     
     */
    public void setRuesCamaras(RuesCamaras value) {
        this.ruesCamaras = value;
    }

    /**
     * Gets the value of the runt property.
     * 
     * @return
     *     possible object is
     *     {@link Runt }
     *     
     */
    public Runt getRunt() {
        return runt;
    }

    /**
     * Sets the value of the runt property.
     * 
     * @param value
     *     allowed object is
     *     {@link Runt }
     *     
     */
    public void setRunt(Runt value) {
        this.runt = value;
    }

    /**
     * Gets the value of the runtPlaca property.
     * 
     * @return
     *     possible object is
     *     {@link RuntPlaca }
     *     
     */
    public RuntPlaca getRuntPlaca() {
        return runtPlaca;
    }

    /**
     * Sets the value of the runtPlaca property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuntPlaca }
     *     
     */
    public void setRuntPlaca(RuntPlaca value) {
        this.runtPlaca = value;
    }

    /**
     * Gets the value of the afiliadosCompensados property.
     * 
     * @return
     *     possible object is
     *     {@link AfiliadosCompensados }
     *     
     */
    public AfiliadosCompensados getAfiliadosCompensados() {
        return afiliadosCompensados;
    }

    /**
     * Sets the value of the afiliadosCompensados property.
     * 
     * @param value
     *     allowed object is
     *     {@link AfiliadosCompensados }
     *     
     */
    public void setAfiliadosCompensados(AfiliadosCompensados value) {
        this.afiliadosCompensados = value;
    }

}
