//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatosTecnicosVehiculo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatosTecnicosVehiculo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capacidadCarga" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pesoBrutoVehicular" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="capacidadPasajeros" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="capacidadPasajerosSentados" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="numeroEjes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatosTecnicosVehiculo", propOrder = {
    "capacidadCarga",
    "pesoBrutoVehicular",
    "capacidadPasajeros",
    "capacidadPasajerosSentados",
    "numeroEjes"
})
public class DatosTecnicosVehiculo {

    protected String capacidadCarga;
    protected String pesoBrutoVehicular;
    protected String capacidadPasajeros;
    protected String capacidadPasajerosSentados;
    protected String numeroEjes;

    /**
     * Gets the value of the capacidadCarga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacidadCarga() {
        return capacidadCarga;
    }

    /**
     * Sets the value of the capacidadCarga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacidadCarga(String value) {
        this.capacidadCarga = value;
    }

    /**
     * Gets the value of the pesoBrutoVehicular property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPesoBrutoVehicular() {
        return pesoBrutoVehicular;
    }

    /**
     * Sets the value of the pesoBrutoVehicular property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPesoBrutoVehicular(String value) {
        this.pesoBrutoVehicular = value;
    }

    /**
     * Gets the value of the capacidadPasajeros property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacidadPasajeros() {
        return capacidadPasajeros;
    }

    /**
     * Sets the value of the capacidadPasajeros property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacidadPasajeros(String value) {
        this.capacidadPasajeros = value;
    }

    /**
     * Gets the value of the capacidadPasajerosSentados property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacidadPasajerosSentados() {
        return capacidadPasajerosSentados;
    }

    /**
     * Sets the value of the capacidadPasajerosSentados property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacidadPasajerosSentados(String value) {
        this.capacidadPasajerosSentados = value;
    }

    /**
     * Gets the value of the numeroEjes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroEjes() {
        return numeroEjes;
    }

    /**
     * Sets the value of the numeroEjes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroEjes(String value) {
        this.numeroEjes = value;
    }

}
