//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:28 AM(foreman)- (JAXB RI IBM 2.2.3-11/28/2011 06:21 AM(foreman)-)
//


package com.grupobancolombia.intf.cliente.gestionriesgo.consultafuentespublicasexternas.v1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Pension complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Pension">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="regimen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="administradora" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="afiliacion" type="{http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0}Afiliacion" minOccurs="0"/>
 *         &lt;element name="afiliacionSubsidiada" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Pension", propOrder = {
    "regimen",
    "administradora",
    "afiliacion",
    "afiliacionSubsidiada"
})
public class Pension {

    protected String regimen;
    protected String administradora;
    protected Afiliacion afiliacion;
    protected String afiliacionSubsidiada;

    /**
     * Gets the value of the regimen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegimen() {
        return regimen;
    }

    /**
     * Sets the value of the regimen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegimen(String value) {
        this.regimen = value;
    }

    /**
     * Gets the value of the administradora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdministradora() {
        return administradora;
    }

    /**
     * Sets the value of the administradora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdministradora(String value) {
        this.administradora = value;
    }

    /**
     * Gets the value of the afiliacion property.
     * 
     * @return
     *     possible object is
     *     {@link Afiliacion }
     *     
     */
    public Afiliacion getAfiliacion() {
        return afiliacion;
    }

    /**
     * Sets the value of the afiliacion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Afiliacion }
     *     
     */
    public void setAfiliacion(Afiliacion value) {
        this.afiliacion = value;
    }

    /**
     * Gets the value of the afiliacionSubsidiada property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfiliacionSubsidiada() {
        return afiliacionSubsidiada;
    }

    /**
     * Sets the value of the afiliacionSubsidiada property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfiliacionSubsidiada(String value) {
        this.afiliacionSubsidiada = value;
    }

}
