<?xml version="1.0" encoding="UTF-8"?>
<definitions name="ConsultaFuentesPublicasExternas" targetNamespace="http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/Enlace/V1.0" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:tns="http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/Enlace/V1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0">
  <import namespace="http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0" location="localhost.ConsultaFuentesPublicasExternasPortType.9081.wsdl">
    </import>
  <binding name="ConsultaFuentesPublicasExternasHttpPortBinding" type="ns1:ConsultaFuentesPublicasExternas">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="consultarFuentesExternas">
      <soap:operation soapAction="http://grupobancolombia.com/intf/Cliente/GestionRiesgo/ConsultaFuentesPublicasExternas/V1.0/consultarFuentesExternas"/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="SystemExceptionMsg">
        <soap:fault name="SystemExceptionMsg" use="literal"/>
      </fault>
    </operation>
  </binding>
  <service name="ConsultaFuentesPublicasExternas">
    <port name="ConsultaFuentesPublicasExternasHttpPort" binding="tns:ConsultaFuentesPublicasExternasHttpPortBinding">
      <soap:address location="http://localhost:9081/DummyFuentesExternas/ConsultaFuentesPublicasExternas"/>
    </port>
  </service>
</definitions>
